---
title: "hypoxia_postprocessing"
output: html_document
---

```{r}
#Note that not all of these packages were not necessary for the analysis

#knitr::opts_chunk$set(echo = TRUE)
# install.packages("knitr")
#  install.packages("ggplot2")
#  install.packages("dplyr")
#  install.packages("readxl")
#  install.packages("lemon")
#  install.packages("gplots")
# install.packages("ggsurvfit")
# install.packages("forcats")
# #install.packages(c("MCMCpack", "matrixStats", "robustbase", "aod", "e1071"))
# #devtools::install_github("holab-hku/DCATS")
# install.packages("cowplot")
# install.packages("tidyverse")
# install.packages("Cairo")
# install.packages("ggbreak")
# install.packages("Seurat")

```

```{r load_color_palette}

load("C:/Users/is427866/Documents/hypoxia/data/colours_accent_8.RData")

```

```{r draw_label_theme_function}
library(tidyverse)
library(cowplot)

draw_label_theme <- function(label, theme = NULL, element = "text", ...) {
  if (is.null(theme)) {
    theme <- ggplot2::theme_get()
  }
  if (!element %in% names(theme)) {
    stop("Element must be a valid ggplot theme element name")
  }

  elements <- ggplot2::calc_element(element, theme)

  cowplot::draw_label(label, 
                      fontfamily = elements$family,
                      fontface = elements$face,
                      colour = elements$color,
                      size = elements$size,
                      ...
  )
}
```


```{r read_in_fixed_area_size}
library(readxl)
library(dplyr)
library(ggplot2)

#Read in data with new Area sizes
df_new_area <- list.files(path="C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/QuPath results with machine learning/Excels from QuPath with new scale/counts/", full.names = TRUE) %>% 
  lapply(read.csv2) %>% # modify read.csv to read_xlxs or other if needed
  bind_rows 

#df_new_area[,c("Class", "Object.ID", "Parent", "ROI")] <- NULL

df_new_area$Image <- gsub(".tif", "", df_new_area$Image)
df_new_area$Image_TMA <- paste(df_new_area$TMA, df_new_area$Image, sep="_")
df_new_area$Image_TMA_hypoxia <- paste(df_new_area$TMA, df_new_area$Image, df_new_area$Name, sep="_")

df_new_area <- df_new_area[order(df_new_area$`Image_TMA`),]

# subset based on hypoksia status
df_high_hypoksia_only <- subset(df_new_area, Name == "High hypoxia")
df_high_hypoksia_only <- df_high_hypoksia_only[order(df_high_hypoksia_only$`Image_TMA`),]
samples_with_high_hypoksia <- df_high_hypoksia_only$Image_TMA

# select samples 
df_low_hypoksia_only <- subset(df_new_area, Name == "Low hypoxia")
df_low_hypoksia_only <- subset(df_low_hypoksia_only, Image_TMA %in% samples_with_high_hypoksia)
df_low_hypoksia_only <- df_low_hypoksia_only[order(df_low_hypoksia_only$`Image_TMA`),]

# Vähennä low hypoksiasta high hypoksia arvot
  # alueen koko
low_h <- as.numeric(df_low_hypoksia_only$Area.µm.2) - as.numeric(df_high_hypoksia_only$Area.µm.2)
df_low_hypoksia_only_fixed <- df_low_hypoksia_only
df_low_hypoksia_only_fixed[, "Area.µm.2"] <- low_h

  # solut
df_low_hypoksia_only_fixed$Num.Detections <- df_low_hypoksia_only$Num.Detections - df_high_hypoksia_only$Num.Detections
df_low_hypoksia_only_fixed$Num.M1.macrophage <- df_low_hypoksia_only$Num.M1.macrophage - df_high_hypoksia_only$Num.M1.macrophage
df_low_hypoksia_only_fixed$Num.M1.microglia <- df_low_hypoksia_only$Num.M1.microglia - df_high_hypoksia_only$Num.M1.microglia
df_low_hypoksia_only_fixed$Num.M2.macrophage <- df_low_hypoksia_only$Num.M2.macrophage - df_high_hypoksia_only$Num.M2.macrophage
df_low_hypoksia_only_fixed$Num.Monocyte <- df_low_hypoksia_only$Num.Monocyte - df_high_hypoksia_only$Num.Monocyte
df_low_hypoksia_only_fixed$Num.Other.cell <- df_low_hypoksia_only$Num.Other.cell - df_high_hypoksia_only$Num.Other.cell
df_low_hypoksia_only_fixed$Num.Other.immune.cell <- df_low_hypoksia_only$Num.Other.immune.cell - df_high_hypoksia_only$Num.Other.immune.cell
df_low_hypoksia_only_fixed$Num.Granulocyte <- df_low_hypoksia_only$Num.Granulocyte - df_high_hypoksia_only$Num.Granulocyte
df_low_hypoksia_only_fixed$Num.M2.microglia <- df_low_hypoksia_only$Num.M2.microglia - df_high_hypoksia_only$Num.M2.microglia
df_low_hypoksia_only_fixed$Num.cDC1 <- df_low_hypoksia_only$Num.cDC1 - df_high_hypoksia_only$Num.cDC1
df_low_hypoksia_only_fixed$Num.cDC2 <- df_low_hypoksia_only$Num.cDC2 - df_high_hypoksia_only$Num.cDC2

# combine corrected low hypoxia with those that have no high hypoksia
temp <- which(df_new_area$Image_TMA_hypoxia %in% df_low_hypoksia_only_fixed$Image_TMA_hypoxia)

df_new_area_fixed <- df_new_area

for (i in temp){
  n <- df_new_area_fixed[i, "Image_TMA_hypoxia"]
  rown <- which(df_low_hypoksia_only_fixed$Image_TMA_hypoxia == n)
  df_new_area_fixed[i,] <- df_low_hypoksia_only_fixed[rown,]
}

df_new_area_fixed$X <- NULL
df_new_area_fixed$X.1 <- NULL

```


```{r preprocessing_of_data}
library(readxl)
library(dplyr)
library(ggplot2)
#library(Cairo)

#load data

#df <- as.data.frame(read_xlsx("/lustre/compbio/projects/Multiplex_ihc_image_analysis/postprocessing/hypoxia_project/data/QuPath_results_Whole_data_set_new.xlsx"))
#df <- read_xlsx("/lustre/compbio/projects/Multiplex_ihc_image_analysis/postprocessing/hypoxia_project/data/QuPath_fixed_cell_classifier_results_Whole data set_new.xlsx")
df <- read_xlsx("C:/Users/is427866/Downloads/QuPath fixed cell classifier results_Whole data set_new.xlsx")

# Load metadata (age, sex, survival time), create relapse classes
meta_df <- read_xlsx("C:/Users/is427866/Documents/hypoxia/hypoxia_sample_metadata_withNew.xlsx")
meta_df$relapse <- c("relapse")
meta_df[which(meta_df$`Prim vs relapse, 1=PRIM, >1=relapse` == "1"), "relapse"] <- c("primary")

path_anno_df <- subset(df, Name == "PathAnnotationObject")

# change missing cell count values to 0

subset_df <- as.data.frame(df[,12:26])
subset_df <- subset_df %>% replace(is.na(.), 0)
df[,12:26] <- subset_df

df <- df[complete.cases(df), ]
df$Core.identifier <- paste(df$`TMA`, df$`Code on TMA`, sep = " ")
df$Core.identifier.hypoxia <- paste(df$`TMA`, df$`Code on TMA`, df$Name, sep = " ")

df$`Area px^2` <- as.numeric(df$`Area px^2`)

# subset based on hypoksia status
df_high_hypoksia_only <- subset(df, Name == "High hypoxia")
df_high_hypoksia_only <- df_high_hypoksia_only[order(df_high_hypoksia_only$`Core.identifier`),]
samples_with_high_hypoksia <- df_high_hypoksia_only$Core.identifier

# select samples 
df_low_hypoksia_only <- subset(df, Name == "Low hypoxia")
df_low_hypoksia_only <- subset(df_low_hypoksia_only, Core.identifier %in% samples_with_high_hypoksia)
df_low_hypoksia_only <- df_low_hypoksia_only[order(df_low_hypoksia_only$`Core.identifier`),]

# Vähennä low hypoksiasta high hypoksia arvot
  # alueen koko
low_h <- as.numeric(df_low_hypoksia_only$`Area px^2`) - as.numeric(df_high_hypoksia_only$`Area px^2`)
df_low_hypoksia_only_fixed <- df_low_hypoksia_only
df_low_hypoksia_only_fixed[, "Area px^2"] <- low_h

  # solut
df_low_hypoksia_only_fixed$`Num Detections` <- df_low_hypoksia_only$`Num Detections` - df_high_hypoksia_only$`Num Detections`
df_low_hypoksia_only_fixed$`Num M1 macrophage` <- df_low_hypoksia_only$`Num M1 macrophage` - df_high_hypoksia_only$`Num M1 macrophage`
df_low_hypoksia_only_fixed$`Num M1 microglia` <- df_low_hypoksia_only$`Num M1 microglia` - df_high_hypoksia_only$`Num M1 microglia`
df_low_hypoksia_only_fixed$`Num M2 macrophage` <- df_low_hypoksia_only$`Num M2 macrophage` - df_high_hypoksia_only$`Num M2 macrophage`
df_low_hypoksia_only_fixed$`Num Monocyte` <- df_low_hypoksia_only$`Num Monocyte` - df_high_hypoksia_only$`Num Monocyte`
df_low_hypoksia_only_fixed$`Num Other cell` <- df_low_hypoksia_only$`Num Other cell` - df_high_hypoksia_only$`Num Other cell`
df_low_hypoksia_only_fixed$`Num Other immune cell` <- df_low_hypoksia_only$`Num Other immune cell` - df_high_hypoksia_only$`Num Other immune cell`
df_low_hypoksia_only_fixed$`Num Granulocyte` <- df_low_hypoksia_only$`Num Granulocyte` - df_high_hypoksia_only$`Num Granulocyte`
df_low_hypoksia_only_fixed$`Num M2 microglia` <- df_low_hypoksia_only$`Num M2 microglia` - df_high_hypoksia_only$`Num M2 microglia`
df_low_hypoksia_only_fixed$`Num cDC1` <- df_low_hypoksia_only$`Num cDC1` - df_high_hypoksia_only$`Num cDC1`
#df_low_hypoksia_only_fixed$`Num cDC2` <- df_low_hypoksia_only$`Num cDC2` - df_high_hypoksia_only$`Num cDC2`

# combine corrected low hypoxia with those that have no high hypoksia
temp <- which(df$Core.identifier.hypoxia %in% df_low_hypoksia_only_fixed$Core.identifier.hypoxia)

df_fixed <- df

for (i in temp){
  n <- as.character(df_fixed[i, "Core.identifier.hypoxia"])
  rown <- which(df_low_hypoksia_only_fixed$Core.identifier.hypoxia == n)
  df_fixed[i,] <- df_low_hypoksia_only_fixed[rown,]
}

new_df <- df_fixed
new_df$Core.identifier.hypoxia <- NULL

# remove samples with no hypoksia

test <- which(as.data.frame(table(new_df$Core.identifier))$Freq <3) 
temp <- as.data.frame(table(new_df$Core.identifier))
remove <- as.character(temp[test,"Var1"])
keep <- c(unique(new_df$Core.identifier))
keep <- setdiff(keep, unique(remove))

final_df <- subset(new_df, new_df$Core.identifier %in% keep)

final_df_removed <- subset(new_df, `Core.identifier` %in% temp[test,"Var1"])

```


```{r filter_out_samples_with_low_counts_and_no_hypoxia}

temp <- which(final_df$Name == "Low hypoxia" & final_df$`Num Detections`==0)
dropout <- final_df[temp,"Core.identifier"]

final_df_filttered <- subset(final_df, !(Core.identifier %in% dropout))

# temp <- which(final_df_filttered$`Num Detections` < 20)
# modified_for_ct <- final_df_filttered
# modified_for_ct[temp, 13:22] <- 0

# Take out those which have less than 20 cells in an hypoxia-area
modified_for_ct <- subset(final_df_filttered, final_df_filttered$`Num Detections` > 19)
temp <- subset(final_df_filttered, final_df_filttered$`Num Detections` < 20)
# Remove those with missing IDH-status
modified_for_ct <- subset(modified_for_ct, `IDH 0=WT, 1=MUT, NA` != "NA")

# Remove grade 1 samples
modified_for_ct_OG <- subset(modified_for_ct, Grade != "1")

## Change M1 and M2 to CD163- and CD163+

colnames(modified_for_ct_OG) <- c("TMA", "Code on TMA", "Tumor type", "Grade", "PAD", "Image name", 
               "Sample code", "IDH 0=WT, 1=MUT, NA", "Prim vs relapse, 1=PRIM, >1=relapse", 
               "Source.Name", "Image", "Name", "Num Detections", "Num CD163- macrophage", 
               "Num CD163- microglia", "Num CD163+ macrophage", "Num Monocyte", "Num Other cell", 
               "Num Other immune cell", "Num Granulocyte", "Num CD163+ microglia", 
               "Num cDC1", "Centroid X px", "Centroid Y px", "Area px^2", 
               "Perimeter px", "Core.identifier")

```


```{r merge_IDHmut_to_OLD_df}

#When using only TMA:
modified_for_ct <- modified_for_ct_OG

# Make all IDH-wt gr 2-3 tumors gr 4
modified_for_ct$Grade <- as.numeric(modified_for_ct$Grade)
temp <- which(modified_for_ct$`IDH 0=WT, 1=MUT, NA` == "0" & modified_for_ct$Grade < 4)
modified_for_ct[temp,"Grade"] <- c(4)

# TMA is not combined into data!!!
       # if you use this, remember to re-run the preprocessing - this overwrites it.

# get counts of immune cells
modified_for_ct$immune_cell_count <- modified_for_ct$`Num Detections` - modified_for_ct$`Num Other cell`

# get total counts of macrophages and microglia
modified_for_ct$macrophage_count <- modified_for_ct$`Num CD163- macrophage` + modified_for_ct$`Num CD163+ macrophage`
modified_for_ct$microglia_count <- modified_for_ct$`Num CD163- microglia` + modified_for_ct$`Num CD163+ microglia`

# Combine new area size to dataframe
modified_for_ct$comb_for_new_size <- paste(modified_for_ct$TMA, modified_for_ct$`Image name`, modified_for_ct$Name, sep = "_")
modified_for_ct <- merge(modified_for_ct, df_new_area_fixed[,c(13,20)], by.x = "comb_for_new_size", by.y = "Image_TMA_hypoxia")

#setdiff(modified_for_ct$comb_for_new_size, df_new_area$Image_TMA)

modified_for_ct$comb_for_new_size <- NULL

```


```{r calc_celltype_fractions_NO_OTHER}
library(data.table)
library(reshape2)
# remove CD45- cells (aka other and cancer cells)
plot_df <- subset(modified_for_ct, Name != "PathAnnotationObject")
#plot_df <- subset(plot_df, `IDH 0=WT, 1=MUT, NA` == "0")
plot_df <- plot_df[,-18] # make sure other cells are column 18!

# merge metadata and remove samples from IDHwt under 20 y.o.
signif_test_df <- merge(plot_df, meta_df[,c(1, 12:15)], by.x = "Core.identifier", by.y = "TMA_code", all.x = T)
signif_test_df$Ikä <- as.numeric(signif_test_df$Ikä)
temp <- which(signif_test_df$`IDH 0=WT, 1=MUT, NA` == "0" & (signif_test_df$Ikä < 20 | is.na(signif_test_df$Ikä)))

if(length(temp)!=0){
  plot_df <- signif_test_df[-temp,]
}else{
  plot_df <- signif_test_df
}

test <- melt(plot_df, measure.vars = c(15:22))
test$variable <- gsub("Num ", "", test$variable)

test$fraction_in_sample <- 0
test$fraction_in_hypoxia_class <- 0
test$fraction_in_hypoxia_class_total <- 0
test$fraction_in_hypoxia_class_total_idh <- 0

for (i in 0:length(test$Core.identifier)) {
  n <- test[i,1]
  temp <- which(test[,1] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_sample"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  m <- test[i,1]
  temp <- which(test[,13] == n & test[,1] == m)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  temp <- which(test[,13] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class_total"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  m <- test[i,9]
  temp <- which(test[,13] == n & test[,9] == m)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class_total_idh"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100

}

shared_data <- test

shared_data <- shared_data %>% replace(is.na(.), 0)
shared_data[,c(16,15)] <- NULL

shared_data_Immune <- shared_data
#write.csv(shared_data, file = "C:/Users/is427866/Downloads/hypoxia_cell_fractions_pathAnnotation_object.csv")

```

```{r calc_celltype_fractions_WITH_OTHER}
library(data.table)
library(reshape2)

plot_df <- subset(modified_for_ct, Name != "PathAnnotationObject")
#plot_df <- subset(plot_df, `IDH 0=WT, 1=MUT, NA` == "1")
#plot_df <- plot_df[,-18] # comment this out if you want other cells to be included, make sure other cells are column 18!

# merge metadata and remove samples from IDHwt under 20 y.o.
signif_test_df <- merge(plot_df, meta_df[,c(1, 12:15)], by.x = "Core.identifier", by.y = "TMA_code", all.x = T)
signif_test_df$Ikä <- as.numeric(signif_test_df$Ikä)
temp <- which(signif_test_df$`IDH 0=WT, 1=MUT, NA` == "0" & (signif_test_df$Ikä < 20 | is.na(signif_test_df$Ikä)))

if(length(temp)!=0){
  plot_df <- signif_test_df[-temp,]
}else{
  plot_df <- signif_test_df
}

#plot_df <- plot_df[,c(4,28,8,9,12,16:24,27)] # Modify these if other cells!
rownames(plot_df) <- make.names(plot_df$Core.identifier, unique = TRUE)
test <- melt(plot_df, measure.vars = c(15:23))
test$variable <- gsub("Num ", "", test$variable)

test$fraction_in_sample <- 0
test$fraction_in_hypoxia_class <- 0
test$fraction_in_hypoxia_class_total <- 0
test$fraction_in_hypoxia_class_total_idh <- 0

for (i in 0:length(test$Core.identifier)) {
  n <- test[i,1]
  temp <- which(test[,1] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_sample"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  m <- test[i,1]
  temp <- which(test[,13] == n & test[,1] == m)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  temp <- which(test[,13] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class_total"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  m <- test[i,9]
  temp <- which(test[,13] == n & test[,9] == m)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class_total_idh"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100

}

shared_data <- test

shared_data <- shared_data %>% replace(is.na(.), 0)
shared_data[,c(14,15)] <- NULL

shared_data_Other <- shared_data
#write.csv(shared_data, file = "C:/Users/is427866/Downloads/hypoxia_cell_fractions_Anni.csv")

```

```{r cell_density}
# Calculate cell densities
library(data.table)
library(reshape2)

plot_df <- subset(modified_for_ct, Name != "PathAnnotationObject")

# merge metadata and remove samples from IDHwt under 20 y.o.
signif_test_df <- merge(plot_df, meta_df[,c(1, 12:15)], by.x = "Core.identifier", by.y = "TMA_code", all.x = T)
signif_test_df$Ikä <- as.numeric(signif_test_df$Ikä)
temp <- which(signif_test_df$`IDH 0=WT, 1=MUT, NA` == "0" & (signif_test_df$Ikä < 20 | is.na(signif_test_df$Ikä)))

if(length(temp)!=0){
  plot_df <- signif_test_df[-temp,]
}else{
  plot_df <- signif_test_df
}

plot_df$`Area.µm.2` <- as.numeric(plot_df$`Area.µm.2`)

plot_df$density_all_cells_per10000um <- (plot_df$`Num Detections`/plot_df$`Area.µm.2`)*10000
plot_df$density_immune_cells_per10000um  <- (plot_df$immune_cell_count/plot_df$`Area.µm.2`)*10000

plot_df_density <- plot_df

#plot_df <- plot_df[,c(4,28,8,9,12,16:24,27)] # Modify these if other cells!
rownames(plot_df) <- make.names(plot_df$Core.identifier, unique = TRUE)
test <- reshape2::melt(plot_df, measure.vars = c(15:23))
test$variable <- gsub("Num ", "", test$variable)

test$density <- 0

for (i in 0:length(test$Core.identifier)) {
  test[i,"density"] <- (test[i,"value"]/test[i,"Area.µm.2"])*10000
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  

}

shared_data <- test

shared_data <- shared_data %>% replace(is.na(.), 0)
shared_data[,c(15,16)] <- NULL

shared_data_density <- shared_data
#write.csv(shared_data, file = "C:/Users/is427866/Downloads/hypoxia_cell_fractions_Anni.csv")



```


```{r individual_celltypes_boxplots_IDH_status_setup, fig.width=8, fig.height=4}
library(ggplot2)

test <- shared_data_density

# Create grouping factor which considers grade and IDH-status
# test$grade_status_for_plot <- c(NA)
# test[which(test$Grade == 1 & test$`IDH 0=WT, 1=MUT, NA`== 0),"grade_status_for_plot"] <- "Grade 1, IDHwt"
# test[which((test$Grade == 2 | test$Grade == 3) & test$`IDH 0=WT, 1=MUT, NA`== 0),"grade_status_for_plot"] <- "Grade 2-3, IDHwt"
# test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 0),"grade_status_for_plot"] <- "Grade 4, IDHwt"
# 
# test[which(test$Grade == 1 & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot"] <- "Grade 1, IDHmut"
# test[which((test$Grade == 2 | test$Grade == 3) & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot"] <- "Grade 2-3, IDHmut"
# test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot"] <- "Grade 4, IDHmut"

# Create grouping factor which considers grade, this overwrites the above!!!!
test$grade_status_for_plot <- c(NA)
test[which(test$Grade == 1),"grade_status_for_plot"] <- "Grade 1"
test[which(test$Grade == 2 | test$Grade == 3),"grade_status_for_plot"] <- "Grade 2-3"
test[which(test$Grade == 4),"grade_status_for_plot"] <- "Grade 4"

# Relapse
test$relapse_simple <- NA
test[which(test$`Prim vs relapse, 1=PRIM, >1=relapse` != 1),"relapse_simple"] <- "Relapse"
test[which(test$`Prim vs relapse, 1=PRIM, >1=relapse` == 1),"relapse_simple"] <- "Primary"

# Create grouping factor which considers hypoxia class and IDH-status
test$group_for_plot <- c(NA)
test[which(test$Name == "Non hypoxic" & test$`IDH 0=WT, 1=MUT, NA`== 0),"group_for_plot_IDH"] <- "Normoxic, IDHwt"
test[which(test$Name == "Low hypoxia" & test$`IDH 0=WT, 1=MUT, NA`== 0),"group_for_plot_IDH"] <- "Low hypoxia, IDHwt"
test[which(test$Name == "High hypoxia" & test$`IDH 0=WT, 1=MUT, NA`== 0),"group_for_plot_IDH"] <- "High hypoxia, IDHwt"

test[which(test$Name == "Non hypoxic" & test$`IDH 0=WT, 1=MUT, NA`== 1),"group_for_plot_IDH"] <- "Normoxic, IDHmut"
test[which(test$Name == "Low hypoxia" & test$`IDH 0=WT, 1=MUT, NA`== 1),"group_for_plot_IDH"] <- "Low hypoxia, IDHmut"
test[which(test$Name == "High hypoxia" & test$`IDH 0=WT, 1=MUT, NA`== 1),"group_for_plot_IDH"] <- "High hypoxia, IDHmut"

# Create grouping factor for hypoxia and relapse
test$group_for_plot_relapse <- c(NA)
test[which(test$Name == "Non hypoxic" & test$relapse_simple == "Primary"),"group_for_plot_relapse"] <- "Normoxic, Primary"
test[which(test$Name == "Low hypoxia" & test$relapse_simple == "Primary"),"group_for_plot_relapse"] <- "Low hypoxia, Primary"
test[which(test$Name == "High hypoxia" & test$relapse_simple == "Primary"),"group_for_plot_relapse"] <- "High hypoxia, Primary"

test[which(test$Name == "Non hypoxic" & test$relapse_simple == "Relapse"),"group_for_plot_relapse"] <- "Normoxic, Relapse"
test[which(test$Name == "Low hypoxia" & test$relapse_simple == "Relapse"),"group_for_plot_relapse"] <- "Low hypoxia, Relapse"
test[which(test$Name == "High hypoxia" & test$relapse_simple == "Relapse"),"group_for_plot_relapse"] <- "High hypoxia, Relapse"

test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 0),"grade_status_for_plot_IDH"] <- "Grade 4, IDHwt"
 
test[which(test$Grade == 1 & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot_IDH"] <- "Grade 1, IDHmut"
test[which((test$Grade == 2 | test$Grade == 3) & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot_IDH"] <- "Grade 2-3, IDHmut"
test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 1),"grade_status_for_plot_IDH"] <- "Grade 4, IDHmut"

test[which((test$Grade == 2 | test$Grade == 3) & test$`IDH 0=WT, 1=MUT, NA`== 1 & test$Name == "Non hypoxic"),"grade_status_for_plot_IDH_hypoxia"] <- "Grade 2-3, Normoxic, IDHmut"
test[which((test$Grade == 2 | test$Grade == 3) & test$`IDH 0=WT, 1=MUT, NA`== 1 & test$Name == "Low hypoxia"),"grade_status_for_plot_IDH_hypoxia"] <- "Grade 2-3, Low hypoxia, IDHmut"
test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 1 & test$Name == "Non hypoxic"),"grade_status_for_plot_IDH_hypoxia"] <- "Grade 4, Normoxic, IDHmut"
test[which(test$Grade == 4 & test$`IDH 0=WT, 1=MUT, NA`== 1 & test$Name == "Low hypoxia"),"grade_status_for_plot_IDH_hypoxia"] <- "Grade 4, Low hypoxia, IDHmut"

```

Below is an example of statistic calculations. The groups for which the 
statistics were calculated (e.g. Normoxic, IDHwt vs Low hypoxia, IDHwt)
were modified while the rest of the script stayed the same.

```{r STAT_individual_celltypes_boxplots_IDH_hypoxia}
# Add signifigance testing

# make the result table 
 # res_table <- as.data.frame(matrix(ncol = 1, nrow = length(unique(test$variable))))
 # rownames(res_table) <- unique(test$variable)
 # colnames(res_table) <- c("Norm - Low, IDHwt")

#test_sub <- test[which(test$group_for_plot_IDH == "Normoxic, IDHmut" | test$group_for_plot_IDH == "Low hypoxia, IDHmut"),]
#test_sub <- test[which(test$group_for_plot_IDH == "Normoxic, IDHmut" | test$group_for_plot_IDH == "High hypoxia, IDHmut"),]
#test_sub <- test[which(test$group_for_plot_IDH == "Low hypoxia, IDHmut" | test$group_for_plot_IDH == "High hypoxia, IDHmut"),]

#test_sub <- test[which(test$group_for_plot_IDH == "Normoxic, IDHwt" | test$group_for_plot_IDH == "Low hypoxia, IDHwt"),]
#test_sub <- test[which(test$group_for_plot_IDH == "Normoxic, IDHwt" | test$group_for_plot_IDH == "High hypoxia, IDHwt"),]
#test_sub <- test[which(test$group_for_plot_IDH == "Low hypoxia, IDHwt" | test$group_for_plot_IDH == "High hypoxia, IDHwt"),]

#test_sub <- test[which(test$group_for_plot_IDH == "Normoxic, IDHmut"  | test$group_for_plot_IDH == "Normoxic, IDHwt"),]
#test_sub <- test[which(test$group_for_plot_IDH == "Low hypoxia, IDHmut" | test$group_for_plot_IDH == "Low hypoxia, IDHwt"),]
#test_sub <- test[which(test$group_for_plot_IDH == "High hypoxia, IDHmut" | test$group_for_plot_IDH == "High hypoxia, IDHwt"),]

#test_sub <- test[which(test$grade_status_for_plot_IDH_hypoxia == "Grade 2-3, Normoxic, IDHmut" | test$grade_status_for_plot_IDH_hypoxia == "Grade 2-3, Low hypoxia, IDHmut"),]
test_sub <- test[which(test$grade_status_for_plot_IDH_hypoxia == "Grade 4, Normoxic, IDHmut" | test$grade_status_for_plot_IDH_hypoxia == "Grade 4, Low hypoxia, IDHmut"),]

#res_table$`Norm - High, IDHmut` <- NA
#res_table$`Low - High, IDHmut` <- NA

#res_table$`Norm - Low, IDHwt` <- NA
#res_table$`Norm - High, IDHwt` <- NA
#res_table$`Low - High, IDHwt` <- NA

#res_table$`IDHmut - IDHwt, Norm` <- NA
#res_table$`IDHmut - IDHwt, Low` <- NA
#res_table$`IDHmut - IDHwt, High` <- NA

#res_table$`Norm - Low, IDHmut, Grade 2-3` <- NA
#res_table$`Norm - Low, IDHmut, Grade 4` <- NA

#res_table$`Norm - Low, IDHmut, Grade 2-3, Total density` <- NA
res_table$`Norm - Low, IDHmut, Grade 4` <- NA

p_values <- numeric(length(unique(test_sub$variable)))

m <- 5

for (ct in unique(test_sub$variable)) {
   
  sub <- subset(test_sub, test_sub$variable == ct)
  #sub_test <- dcast(sub, Name ~ fraction_in_hypoxia_class)
  print(ct)
  
  sub$Name <- as.factor(sub$Name)
  
  # Wilcoxon
  #res <- wilcox.test(density_all_cells_per10000um ~ group_for_plot_IDH, data=sub) uncomment if calculating general density  
  #res <- wilcox.test(density_immune_cells_per10000um ~ group_for_plot_IDH, data=sub)
  res <- wilcox.test(density ~ group_for_plot_IDH, data=sub)
  
  text <- paste("W = ", res$statistic, ", p-value = ", res$p.value, sep = "")
  print(text)
  
  # Store p-value
  p_values[ct] <- res$p.value
  
  n <- which(rownames(res_table) == ct)
  res_table[n,m] <- text
}

# Apply p-value correction (Benjamini-Hochberg FDR)
p_adjusted <- p.adjust(p_values, method = "BH")

# Add adjusted p-values to results table
for (ct in unique(test_sub$variable)) {
  n <- which(rownames(res_table) == ct)
  res_table[n,m] <- paste(res_table[n,m], ", p.adj = ", p_adjusted[ct], sep = "")
}

res_table

#write.csv(res_table, "C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/Wilcox_boxplots_celltypes_IDH_hypoxia_statistics_TOTAL_CELL.csv")

```

# Visualizations

```{r VIZ_celltypes_in_hypoxia_barplot, fig.height=5, fig.width=5}
#, fig.height=8, fig.width=10}
library(ggplot2)

shared_data <- shared_data_Immune

# in all samples
ggplot(shared_data, aes(x=factor(Core.identifier), y=fraction_in_sample, fill=factor(variable, levels=c("cDC1", "CD163- macrophage", "CD163+ macrophage", "CD163- microglia", "CD163+ microglia", "Granulocyte", "Monocyte", "Other immune cell")))) + geom_bar(stat="identity", position="stack") + scale_fill_discrete(name="Sample") + ggtitle("Cell type frequencies as percentages, percentage per hypoxia class") + theme_classic() + xlab("Hypoxia class") + ylab("Percentage") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) +scale_fill_manual(values=accent_8_colours) + guides(fill=guide_legend(title="Celltype")) 

#ggsave("C:/Users/is427866/Documents/hypoxia/barplots/barplot_celltypes_in_samples.png")
#ggsave("C:/Users/is427866/Documents/hypoxia/barplots/barplot_celltypes_in_samples.pdf")

# across hypoxia classes
plot_df <- shared_data %>% group_by(Name, variable) %>% summarize(percent=sum(fraction_in_hypoxia_class_total))

ggplot(plot_df, aes(x=factor(Name, levels=c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxic", "Low hypoxia", "High hypoxia")), y=percent, fill=factor(variable, levels=c("cDC1", "CD163- macrophage", "CD163+ macrophage", "CD163- microglia", "CD163+ microglia", "Granulocyte", "Monocyte", "Other immune cell", "Other cell")))) + geom_bar(stat="identity", position="stack") + ggtitle("Cell type frequencies as percentages, \npercentage per hypoxia class") + xlab("Hypoxia class") + ylab("Percentage") + theme_classic() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + scale_fill_manual(values=c(accent_8_colours, "#D3D3D3")) + guides(fill=guide_legend(title="Celltype"))
 
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/barplot_celltypes_hypoxia_TMA_fixed.png")
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/barplot_celltypes_hypoxia_TMA_fixed.pdf")


# barplot with counts
plot_df <- aggregate(shared_data$value ~ shared_data$Name + shared_data$variable, shared_data, sum)
colnames(plot_df) <- c("Name", "variable", "counts_withOther")
plot_df$merg <- paste(plot_df$Name, plot_df$variable)
plot_df2 <- plot_df

#savedf <- merge(plot_df, plot_df2, by="merg", all = T)
#aggregate(savedf$counts_withOther ~ savedf$Name.x, savedf, sum)

#write.csv(savedf, "C:/Users/is427866/Documents/hypoxia/cell_type_fractions_in_hypoxia2.csv")

# in hypoxia classes
#ggplot(shared_data, aes(x=factor(Name), y=fraction_in_hypoxia_class_total, fill=variable)) + geom_bar(stat="identity", position="stack") + scale_fill_discrete(name="Sample") + ggtitle("Cell type frequencies as percentages, percentage per hypoxia class") + xlab("Hypoxia class") + ylab("Percentage") + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + scale_fill_manual(values=accent_8_colours) + geom_text(data=plot_df, aes(label=round(fraction_in_hypoxia_class_total,2)), position=position_stack(vjust=0.5)) + theme_classic()

#ggsave(paste("C:/Users/is427866/Documents/hypoxia/", "barplot_celltypes_in_hypoxia", ".pdf", sep = ""))

```

```{r VIZ_hypoxia_size_boxplot, fig.width=8, fig.height=4}
#Here
plot_df <- modified_for_ct[,c(12,31,27,4,8,9)]
plot_df$grade_for_plot <- c(NA)
plot_df[which(plot_df$Grade == 1),"grade_for_plot"] <- "Grade 1"
plot_df[which(plot_df$Grade == 2 | plot_df$Grade == 3),"grade_for_plot"] <- "Grade 2-3"
plot_df[which(plot_df$Grade == 4),"grade_for_plot"] <- "Grade 4"

plot_df <- subset(plot_df, Name != "PathAnnotationObject")
plot_df$`Area.µm.2` <- as.numeric(plot_df$`Area.µm.2`)

plot_df$fraction <- 0
plot_df$fraction_hypoxia <- 0

for (i in 0:length(plot_df$Core.identifier)) {
  n <- plot_df[i,3]
  temp <- which(plot_df[,3] == n)
  temp_sum <- sum(plot_df[temp,2])
  plot_df[i,8] <- (plot_df[i,2]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- plot_df[i,1]
  temp <- which(plot_df[,1] == n)
  temp_sum <- sum(plot_df[temp,2])
  plot_df[i,9] <- (plot_df[i,2]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100

}

plot_df <- subset(plot_df, Grade != 1)

for (g in unique(plot_df$Name)){
  sub <- subset(plot_df, Name==g)
  p <- ggplot(sub, aes(x=grade_for_plot, y=fraction)) + geom_violin() + stat_summary(fun=median, geom="point", size=2, color="red") + geom_jitter(position = position_jitter(0.2, 0)) + labs(title=paste("Area Size in Samples, fraction from samples, ", g),x="Grade", y = "Percentage")
  #print(p)


p <- ggplot(sub, aes(x=grade_for_plot, y=fraction_hypoxia)) + geom_violin() + stat_summary(fun=median, geom="point", size=2, color="red") + geom_jitter(position = position_jitter(0.2, 0)) + labs(title=paste("Area Size in Samples, fraction from ", g),x="Grade", y = "Percentage")
  #print(p)

}

# Mark samples that have areas less than 10% of the core

plot_df$under10percentageSize <- F
plot_df[which(plot_df$fraction < 10), "under10percentageSize"] <- T

# Get age groups 
plot_df <- merge(unique(shared_data[,c(15,18,19)]), plot_df, by= "Area.µm.2")
plot_df$age_for_plot <- c("<= 55")
plot_df[which(plot_df$Ikä > 55),"age_for_plot"] <- c(">55")

plot_df$relapse_simple <- NA
plot_df[which(plot_df$`Prim vs relapse, 1=PRIM, >1=relapse` != 1),"relapse_simple"] <- "Relapse"
plot_df[which(plot_df$`Prim vs relapse, 1=PRIM, >1=relapse` == 1),"relapse_simple"] <- "Primary"

# merge with used data
# test <- shared_data
# test <- merge(shared_data, plot_df[,c(2,9)], by = "Area px^2")

# sum(plot_df[which(plot_df$Name=="Non hypoxic"), "fraction_hypoxia"])
# sum(plot_df[which(plot_df$Name=="Low hypoxia"), "fraction_hypoxia"])
# sum(plot_df[which(plot_df$Name=="High hypoxia"), "fraction_hypoxia"])

#Area Size in Samples, fraction from samples, 
sub_norm <- subset(plot_df, Name=="Non hypoxic")
sub_low <- subset(plot_df, Name=="Low hypoxia")
sub_high <- subset(plot_df, Name=="High hypoxia")

sub_wt <- subset(plot_df, `IDH 0=WT, 1=MUT, NA`==0)

sub_mut <- subset(plot_df, `IDH 0=WT, 1=MUT, NA`==1)

  # p1 <- ggplot(sub_norm, aes(x=grade_for_plot, y=fraction, fill=`IDH 0=WT, 1=MUT, NA`)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("Normoxic"),x="Grade", y = "Percentage")+ ylim(0,100) + theme_classic() + theme(legend.position="none")
  # print(p1)
  # 
  # p2 <- ggplot(sub_low, aes(x=grade_for_plot, y=fraction, fill=`IDH 0=WT, 1=MUT, NA`)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("Low hypoxia"),x="Grade", y = "Percentage")+ ylim(0,100)+ theme_classic() + theme(legend.position="none")
  # print(p2)
  # 
  # p3 <- ggplot(sub_high, aes(x=grade_for_plot, y=fraction, fill=`IDH 0=WT, 1=MUT, NA`)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("High hypoxia"),x="Grade", y = "Percentage") + ylim(0,100) + theme_classic() #+ guides(fill=guide_legend(title="IDH-status")) #+ scale_fill_manual(labels = c("Wild-type", "Mutant"))
  # print(p3)

# GRADE
 p1 <- ggplot(sub_mut, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=grade_for_plot)) + geom_boxplot(outlier.shape = NA) + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-mut"),x="Hypoxia class", y = "Percentage")+ ylim(0,100) + theme_classic() + guides(fill=guide_legend(title="Grade")) + geom_hline(yintercept=10, linetype="dashed", color = "gray") #+ theme(legend.position="none")
# print(p1)
# 
 p2 <- ggplot(sub_wt, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=grade_for_plot)) + geom_boxplot(outlier.shape = NA) + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-wt"),x="Hypoxia class", y = "Percentage")+ ylim(0,100)+ theme_classic() + guides(fill=guide_legend(title="Grade")) + geom_hline(yintercept=10, linetype="dashed", color = "gray") + scale_fill_manual(values=c("#00BFC4")) #+ theme(legend.position="none")
# print(p2)

# AGE
#p1 <- ggplot(sub_mut, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=age_for_plot)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-mut"),x="Hypoxia class", y = "Percentage")+ ylim(0,100) + theme_classic() + guides(fill=guide_legend(title="Age")) #+ theme(legend.position="none")
#print(p1)
 
#p2 <- ggplot(sub_wt, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=age_for_plot)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-wt"),x="Hypoxia class", y = "Percentage")+ ylim(0,100)+ theme_classic() + guides(fill=guide_legend(title="Age")) #+ scale_fill_manual(values=c("#00BFC4")) #+ theme(legend.position="none")
#print(p2)

# RELAPSE
#p1 <- ggplot(sub_mut, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=relapse_simple)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-mut"),x="Hypoxia class", y = "Percentage")+ ylim(0,100) + theme_classic() + guides(fill=guide_legend(title="Relapse status")) #+ theme(legend.position="none")
#print(p1)
 
#p2 <- ggplot(sub_wt, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=relapse_simple)) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-wt"),x="Hypoxia class", y = "Percentage")+ ylim(0,100)+ theme_classic() + guides(fill=guide_legend(title="Relapse status")) #+ scale_fill_manual(values=c("#00BFC4")) #+ theme(legend.position="none")
#print(p2)

# GENDER
 #p1 <- ggplot(sub_mut, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=factor(`Sukupuoli 0=nainen`, labels = c("Female", "Male")))) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-mut"),x="Hypoxia class", y = "Percentage")+ ylim(0,100) + theme_classic() + guides(fill=guide_legend(title="Gender")) #+ theme(legend.position="none")
# print(p1)
# 
 #p2 <- ggplot(sub_wt, aes(x=factor(Name, levels=c("Non hypoxic","Low hypoxia", "High hypoxia")), y=fraction, fill=factor(`Sukupuoli 0=nainen`, labels = c("Female", "Male")))) + geom_boxplot() + geom_jitter(position = position_jitterdodge(0.2, 0)) + labs(title=c("IDH-wt"),x="Hypoxia class", y = "Percentage")+ ylim(0,100)+ theme_classic() + guides(fill=guide_legend(title="Gender")) #+ scale_fill_manual(values=c("#00BFC4")) #+ theme(legend.position="none")
# print(p2)
  
library(cowplot)

p <- plot_grid(p1,p2, ncol = 2)
print(p)
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/Area Size Boxplots/AreaSizeinSamplesFractionFromSamples_Grade_IDH_line_NEW.png")
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/Area Size Boxplots/AreaSizeinSamplesFractionFromSamples_Grade_IDH_line_NEW.pdf")


#Calculate percentage of over 10% samples
# low_wt <- subset(sub_mut, Name == "Low hypoxia")
# low_wt <- subset(low_wt, grade_for_plot=="Grade 2-3")
# n <- length(which(low_wt$under10percentageSize==F))
# m <- length(low_wt$under10percentageSize)
# n/m


```


```{r VIZ_individual_celltypes_boxplots_grade, fig.width=3, fig.height=5}

# Plotting
library(ggbreak)

for (ct in unique(test$variable)) {
  temp_ct <- subset(test, Grade != 1)
  temp_ct <- subset(temp_ct, variable == ct)
  temp_ct <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` != "NA")
  
  sub_mut <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` == "1")
   sub_wt <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` == "0")
    ## PLOT WITH SAME Y AXIS
  # Extract maximum Y-axis values
max_y1 <- max(sub_mut$density)
max_y2 <- max(sub_wt$density)

# Determine the larger Y-axis value
max_y <- max(max_y1, max_y2)
  
    # All samples, split by hypoxia levels and IDH GROUPED
 p1 <- ggplot(sub_mut, aes(x=grade_status_for_plot, y=density, fill = factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxia", "Low hypoxia", "High hypoxia")))) +
   geom_boxplot(outlier.shape = NA) + 
   theme_classic() +
   labs(title=paste("IDHmut"),x="Grade", y = "Cells / 10 000 µm²") +
   guides(fill=guide_legend(title="Group")) +
   geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
   scale_fill_manual(values=accent_8_colours) +
   theme(legend.position="none") #+
   #ylim(0, 55) #+
   #scale_y_break(breaks=c(17, 17), scales = 0.2)
 
 
 # All samples, split by hypoxia levels and IDH GROUPED
  p2 <- ggplot(sub_wt, aes(x=grade_status_for_plot, y=density, fill = factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxia", "Low hypoxia", "High hypoxia")))) +
   geom_boxplot(outlier.shape = NA) + 
   theme_classic() +
   labs(title=paste(ct, ", IDHwt", sep = ""),x="Grade", y = "Cells / 10 000 µm²") +
   guides(fill=guide_legend(title="Group")) +
   geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
   scale_fill_manual(values=accent_8_colours) +
    theme(legend.position="none") +
   ylim(0, 55) +
    scale_y_break(breaks=c(25, 25), scales = 0.2, expand = T)
  print(p2)
    #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/celltypes_sameY_55_cutY_GBonly/", ct, ".pdf", sep = ""))
  #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/celltypes_sameY_55_cutY_GBonly/", ct, ".png", sep = ""))
  
 
  library(cowplot)
  title <- ggdraw() +
  draw_label_theme(paste("Cell type density in hypoxia class", ct, sep = " "), 
                   theme = theme_classic(), element = "plot.title",
                   x = 0.05, hjust = 0, vjust = 1)
  
  p <- plot_grid(title, NULL, p1,p2, ncol = 2,  rel_heights = c(0.1, 1), rel_widths = c(0.80, 1.1))
  #print(p)
  
  #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/all3_hypoxia_celltypes_in_grade_IDH_hypoxia/percentage/", ct, ".png", sep = ""))
  #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/all3_hypoxia_celltypes_in_grade_IDH_hypoxia/percentage/", ct, ".pdf", sep = ""))
  
  #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/celltypes_sameY_55_cutY_GBonly/", ct, ".pdf", sep = ""))
  #ggsave(paste("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/celltypes_sameY_55_cutY_GBonly/", ct, ".png", sep = ""))
  
}

```

```{r VIZ_total_cell_densities, fig.width=5, fig.height=5}
# Plot total cell density
temp_ct <- subset(test, Grade != 1)
temp_ct <- subset(temp_ct, variable == "Other cell")
 sub_wt <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` == "0")
   
ggplot(sub_wt, aes(x=grade_status_for_plot, y=density_immune_cells_per10000um, fill = factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxia", "Low hypoxia", "High hypoxia")))) +
   geom_boxplot(outlier.shape = NA) + 
   theme_classic() +
   labs(title=paste("IDHwt, Total immune cell density"),x="Grade", y = "Cells / 10 000 µm²") +
   guides(fill=guide_legend(title="Group")) +
   geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
   scale_fill_manual(values=accent_8_colours) +
  scale_y_break(breaks=c(75, 75), scales = 0.2, expand = T) +
  ylim(0, 105)

#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/sameY_fig1_immune_cell_density_cutY.pdf")

ggplot(sub_wt, aes(x=grade_status_for_plot, y=density, fill = factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxia", "Low hypoxia", "High hypoxia")))) +
   geom_boxplot(outlier.shape = NA) + 
   theme_classic() +
   labs(title=paste("IDHwt, Other cell density"),x="Grade", y = "Cells / 10 000 µm²") +
   guides(fill=guide_legend(title="Group")) +
   geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
   scale_fill_manual(values=accent_8_colours) +
  scale_y_break(breaks=c(75, 75), scales = 0.2, expand = T) +
  ylim(0, 105)

#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/sameY_fig1_other_cell_density_cutY.pdf")
```

```{r VIZ_immune_cell_density, fig.height=5, fig.width=8}
library(ggplot2)

test <- plot_df_density

test$grade_for_plot <- c(NA)
test[which(test$Grade == 1),"grade_for_plot"] <- "Grade 1"
test[which(test$Grade == 2 | test$Grade == 3),"grade_for_plot"] <- "Grade 2-3"
test[which(test$Grade == 4),"grade_for_plot"] <- "Grade 4"

temp_ct <- subset(test, Grade != 1)
temp_ct <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` != "NA")
temp_ct <- subset(temp_ct, variable == "Other cell") # Select one celltype to avoid duplicating data!

temp_ct_wt <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` == "0")
temp_ct_mut <- subset(temp_ct, `IDH 0=WT, 1=MUT, NA` == "1")

  # Extract maximum Y-axis values
max_y2 <- max(temp_ct_wt$density_immune_cells)
max_y1 <- max(temp_ct_mut$density_immune_cells)

# Determine the larger Y-axis value
max_y <- max(max_y1, max_y2)

# All samples, split by hypoxia levels and IDH GROUPED
p2 <- ggplot(temp_ct_wt, aes(x=grade_for_plot, y=density_immune_cells_per10000um, fill = factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia")))) +
geom_boxplot(outlier.shape = NA) + 
theme_classic() +
labs(title=paste("IDHwt"),x="Grade", y = "Cells / 10 000 µm²") +
guides(fill=guide_legend(title="Group")) +
geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
scale_fill_manual(values=accent_8_colours) +
  ylim(0, max_y) #+
  #scale_y_break(breaks=c(0.0075, 0.015))

print(p2)
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density/immune_cell_density_nm_new_IDHwt_sameY_1510.pdf")

# All samples, split by hypoxia levels and IDH GROUPED
p1 <- ggplot(temp_ct_mut, aes(x=grade_for_plot, y = as.numeric(density_immune_cells_per10000um), fill=factor(Name, levels = c("Non hypoxic", "Low hypoxia", "High hypoxia")))) +
geom_boxplot(outlier.shape = NA) + 
theme_classic() +
labs(title=paste("IDHmut"),x="Grade", y = "Cells / 10 000 µm²") +
guides(fill=guide_legend(title="Group")) +
geom_jitter(position = position_jitterdodge(jitter.width = 0.2, jitter.height = 0)) +
scale_fill_manual(values=accent_8_colours) +
  ylim(0, max_y) +
  theme(legend.position="none") #+
  #scale_y_break(breaks=c(0.0075, 0.015))

print(p1)
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density/immune_cell_density_nm_new_IDHmut_sameY_1510.pdf")

  title <- ggdraw() +
  draw_label_theme(paste("Density of Immune cells", sep = " "), 
                   theme = theme_classic(), element = "plot.title",
                   x = 0.05, hjust = 0, vjust = 1)
  
  p <- plot_grid(title, NULL, p1,p2, ncol = 2,  rel_heights = c(0.1, 1), rel_widths = c(0.80, 1.1))
  print(p)
  

#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/boxplots/cell_density_10000um^2/immune_cell_density_nm_new_IDHseparate_sameY.png")


```


```{r VIZ_barplots}

shared_data_Immune_IDHmut <- subset(shared_data_Other, `IDH 0=WT, 1=MUT, NA` == 1)
shared_data_Immune_IDHwt <- subset(shared_data_Other, `IDH 0=WT, 1=MUT, NA` == 0)

# across hypoxia classes
plot_df <- shared_data_Immune_IDHmut %>% group_by(Name, variable) %>% summarize(percent=sum(fraction_in_hypoxia_class_total_idh))

p1 <- ggplot(plot_df, aes(x=factor(Name, levels=c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxic", "Low hypoxia", "High hypoxia")), y=percent, fill=factor(variable, levels=c("cDC1", "CD163- macrophage", "CD163+ macrophage", "CD163- microglia", "CD163+ microglia", "Granulocyte", "Monocyte", "Other immune cell", "Other cell")))) + geom_bar(stat="identity", position="stack") + ggtitle("IDHmut") + xlab("Hypoxia class") + ylab("Percentage") + theme_classic() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + scale_fill_manual(values=c(accent_8_colours, "#D3D3D3")) + guides(fill=guide_legend(title="Celltype")) + theme(legend.position="none")

plot_df <- shared_data_Immune_IDHwt %>% group_by(Name, variable) %>% summarize(percent=sum(fraction_in_hypoxia_class_total_idh))

p2 <- ggplot(plot_df, aes(x=factor(Name, levels=c("Non hypoxic", "Low hypoxia", "High hypoxia"), labels = c("Normoxic", "Low hypoxia", "High hypoxia")), y=percent, fill=factor(variable, levels=c("cDC1", "CD163- macrophage", "CD163+ macrophage", "CD163- microglia", "CD163+ microglia", "Granulocyte", "Monocyte", "Other immune cell", "Other cell")))) + geom_bar(stat="identity", position="stack") + ggtitle("IDHwt") + xlab("Hypoxia class") + ylab("Percentage") + theme_classic() + theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + scale_fill_manual(values=c(accent_8_colours, "#D3D3D3")) + guides(fill=guide_legend(title="Celltype"))

  title <- ggdraw() +
  draw_label_theme(paste("Cell type frequencies as percentages, percentage per hypoxia class", sep = " "), 
                   theme = theme_classic(), element = "plot.title",
                   x = 0.05, hjust = 0, vjust = 1)
  
  p <- plot_grid(title, NULL, p1,p2, ncol = 2,  rel_heights = c(0.1, 1), rel_widths = c(0.80, 1.1))
  print(p)
 
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/barplot_celltypes_hypoxia_IDHstatus_fixed.png")
#ggsave("C:/Users/is427866/OneDrive - TUNI.fi/Hypoksia projekti/Image analysis/Visualizations, boxplots and barplots/TMA only/barplot_celltypes_hypoxia_IDHstatus_fixed.pdf")
```

## Miscellanous analyses



```{r}
#take only samples with all hypoksia classes

test <- which(as.data.frame(table(modified_for_ct$Core.identifier))$Freq < 4) 
temp <- as.data.frame(table(modified_for_ct$Core.identifier))
remove <- as.character(temp[test,"Var1"])
keep <- c(unique(modified_for_ct$Core.identifier))
keep <- setdiff(keep, unique(remove))

modified_for_ct_all3hypoxia <- subset(modified_for_ct, modified_for_ct$Core.identifier %in% keep)

signif_test_df <- modified_for_ct_all3hypoxia

signif_test_df <- merge(signif_test_df, meta_df[,c(1, 12:15)], by.x = "Core.identifier", by.y = "TMA_code", all.x = T)
signif_test_df$Ikä <- as.numeric(signif_test_df$Ikä)
temp <- which(signif_test_df$`IDH 0=WT, 1=MUT, NA` == "0" & signif_test_df$Ikä < 20)

if(length(temp)!=0){
  plot_df <- signif_test_df[-temp,]
}else{
  plot_df <- signif_test_df
}


```

```{r}
#Calculate cell percentages for upper df of samples with only hypoxia
library(data.table)
library(reshape2)

plot_df <- subset(plot_df, Name != "PathAnnotationObject")

plot_df$`Area.µm.2` <- as.numeric(plot_df$`Area.µm.2`)

plot_df$density_all_cells_per10000um <- (plot_df$`Num Detections`/plot_df$`Area.µm.2`)*10000
plot_df$density_immune_cells_per10000um <- (plot_df$immune_cell_count/plot_df$`Area.µm.2`)*10000

plot_df$density_total_macrophage_per10000um <- (plot_df$macrophage_count/plot_df$`Area.µm.2`)*10000
plot_df$density_total_microglia_per10000um <- (plot_df$microglia_count/plot_df$`Area.µm.2`)*10000

plot_df_density <- plot_df

#plot_df <- plot_df[,c(4,28,8,9,12,16:24,27)] # Modify these if other cells!
rownames(plot_df) <- make.names(plot_df$Core.identifier, unique = TRUE)
test <- melt(plot_df, measure.vars = c(15:23))
test$variable <- gsub("Num ", "", test$variable)

test$density <- 0
test$fraction_in_sample <- 0
test$fraction_in_hypoxia_class <- 0
test$fraction_in_hypoxia_class_total <- 0

for (i in 0:length(test$Core.identifier)) {
  test[i,"density"] <- (test[i,"value"]/test[i,"Area.µm.2"])*10000
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,1]
  temp <- which(test[,1] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_sample"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  m <- test[i,1]
  temp <- which(test[,13] == n & test[,1] == m)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100
  
  n <- test[i,13]
  temp <- which(test[,13] == n)
  temp_sum <- sum(test[temp,"value"])
  test[i,"fraction_in_hypoxia_class_total"] <- (test[i,"value"]/temp_sum)*100
  #table2[i,4] <- (table2[i,3]/re_ordered_n_list[[as.character(n)]])*100

}


shared_data <- test

shared_data <- shared_data %>% replace(is.na(.), 0)
shared_data[,c(15,16)] <- NULL

shared_data_3classes <- shared_data
#write.csv(shared_data, file = "C:/Users/is427866/Downloads/hypoxia_cell_fractions_Anni.csv")


```

```{r}
#Does data have one class of hypoxia but not other?

library(dplyr)

df <- modified_for_ct
# Assuming your dataframe is named df
result <- df %>%
  group_by(Core.identifier) %>%
  summarize(
    has_x = any(Name == "Non hypoxic"),
    has_y = any(Name == "Low hypoxia"),
    has_z = any(Name == "High hypoxia")
  ) %>%
  filter(!has_x & has_y & has_z) %>%
  select(Core.identifier)

print(result)
```


