#!/usr/bin/env bash 


# export JAVA_OPTS="-XX:ParallelGCThreads=4 -XX:ConcGCThreads=4"
# export _JAVA_OPTIONS="-XX:ParallelGCThreads=4 -XX:ConcGCThreads=4 -Djava.util.concurrent.ForkJoinPool.common.parallelism=4"
# export FIJI_OPTS="-XX:ActiveProcessorCount=4"

/home/masi/Software/Fiji.app/ImageJ-linux64 --headless --memory=8000M --run trackmate_script.py


# Usage: /home/masi/Software/Fiji.app/ImageJ-linux64 [<Java options>.. --] [<ImageJ options>..] [<files>..]

# ImageJ launcher 4.0.5 (build 1260)
# Java options are passed to the Java Runtime, ImageJ
# options to ImageJ (or Jython, JRuby, ...).

# In addition, the following options are supported by ImageJ:
# General options:
# --help, -h
# 	show this help
# --dry-run
# 	show the command line, but do not run anything
# --info
# 	informational output
# --debug
# 	verbose output
# --system
# 	do not try to run bundled Java
# --java-home <path>
# 	specify JAVA_HOME explicitly
# --print-java-home
# 	print ImageJ's idea of JAVA_HOME
# --print-ij-dir
# 	print where ImageJ thinks it is located
# --headless
# 	run in text mode
# --ij-dir <path>
# 	set the ImageJ directory to <path> (used to find
# 	 jars/, plugins/ and macros/)
# --heap, --mem, --memory <amount>
# 	set Java's heap size to <amount> (e.g. 512M)
# --class-path, --classpath, -classpath, --cp, -cp <path>
# 	append <path> to the class path
# --jar-path, --jarpath, -jarpath <path>
# 	append .jar files in <path> to the class path
# --pass-classpath
# 	pass -classpath <classpath> to the main() method
# --full-classpath
# 	call the main class with the full ImageJ class path
# --dont-patch-ij1
# 	do not try to runtime-patch ImageJ1
# --ext <path>
# 	set Java's extension directory to <path>
# --default-gc
# 	do not use advanced garbage collector settings by default
# 	(-Xincgc -XX:PermSize=128m)
# --gc-g1
# 	use the G1 garbage collector
# --debug-gc
# 	show debug info about the garbage collector on stderr
# --debugger=<port>[,suspend]
# 	start the JVM in a mode so Eclipse's debugger can attach to it
# --no-splash
# 	suppress showing a splash screen upon startup

# Options for ImageJ:
# --ij2
# 	start ImageJ2 instead of ImageJ1
# --ij1
# 	start ImageJ1
# --allow-multiple
# 	do not reuse existing ImageJ instance
# --plugins <dir>
# 	use <dir> to discover plugins
# --run <plugin> [<arg>]
# 	run <plugin> in ImageJ, optionally with arguments
# --compile-and-run <path-to-.java-file>
# 	compile and run <plugin> in ImageJ
# --edit [<file>...]
# 	edit the given file in the script editor

# Options to run programs other than ImageJ:
# --update
# 	start the command-line version of the ImageJ updater
# --clojure
# 	start Clojure instead of ImageJ (this is the 
# 	default when called with a file ending in .clj)
# --beanshell
# --bsh
# 	start BeanShell instead of ImageJ (this is the
# 	default when called with a file ending in .bs or .bsh
# --main-class <class name> (this is the
# 	default when called with a file ending in .class)
# 	start the given class instead of ImageJ
# --retrotranslator
# 	use Retrotranslator to support Java < 1.6


